### ISSUE TITLE
Naiveproxy必填服务器端口？

### ISSUE THREAD

**Issue by TsXor** [Qv2ray/QvPlugin-NaiveProxy#3]
可以通过编辑json删掉端口，然而分享链接里端口还是443，复制分享链接再导入，端口是443，删掉分享链接里的:443导入，端口也是443，不填就默认为443，然而Naiveproxy并不强制要求服务器端口（我扒下来的这个服务器也没指定端口）
仔细看了下，Naiveproxy的说明也没有明确说出不指定端口默认443
这是什么共识吗？能帮我解个惑不（

**Comment by DuckSoft** [comment]
是本插件的行为之一，明确指定端口是美德。
